alter table ERP_TRAILER add constraint FK_ERP_TRAILER_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID);
alter table ERP_TRAILER add constraint FK_ERP_TRAILER_CURRENCY_BILLING foreign key (CURRENCY_BILLING_ID) references ERP_CURRENCY(ID);
alter table ERP_TRAILER add constraint FK_ERP_TRAILER_FORWARDER foreign key (FORWARDER_ID) references ERP_FORWARDER(ID);
create index IDX_ERP_TRAILER_COMPANY on ERP_TRAILER (COMPANY_ID);
create index IDX_ERP_TRAILER_CURRENCY_BILLING on ERP_TRAILER (CURRENCY_BILLING_ID);
create index IDX_ERP_TRAILER_FORWARDER on ERP_TRAILER (FORWARDER_ID);