create table ERP_TRAILER (
    ID uuid,
	  VERSION integer not null,
	  CREATE_TS timestamp,
	  CREATED_BY varchar(50),
	  UPDATE_TS timestamp,
	  UPDATED_BY varchar(50),
	  DELETE_TS timestamp,
	  DELETED_BY varchar(50),
	  --
    NAME varchar(255) not null,
	  GUID varchar(255),
	  COMPANY_ID uuid not null,
	  TYPE integer not null,
	  IDENT_NUMBER varchar(255),
	  EMPTY_TRAILER_WEIGHT double precision,
	  LENGTH double precision,
	  WIDTH double precision,
	  HEIGHT double precision,
	  COST_KILOMETER double precision,
    COST_HOUR double precision,
    COST_SUPPLY double precision,
    CURRENCY_BILLING_ID uuid,
    MAX_CARGO_COST double precision,
    MAX_WEIGHT double precision,
    MAX_VOLUME double precision,
    MIN_WEIGHT double precision,
    MIN_VOLUME double precision,
    LIMIT_WEIGHT double precision,
    LIMIT_VOLUME double precision,
    MIN_SERVICE_TIME double precision,
    START_TIME time,
    END_TIME time,
    SERVICE_POINTS_WITH_RAMP boolean,
    SERVICE_POINTS_WITHOUT_RAMP boolean,
    START_POINT_ID varchar(255),
    END_POINT_ID varchar(255),
    FORWARDER_ID uuid,
    TEMPERATURE_CONDITIONS boolean,
    TEMPERATURE_RETENTION_TIME integer,
    LOW_TEMPERATURE integer,
    HIGH_TEMPERATURE integer,
    --
	  primary key (ID)
);