alter table ERP_TRANSPORT add constraint FK_ERP_TRANSPORT_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID);
alter table ERP_TRANSPORT add constraint FK_ERP_TRANSPORT_TRANSPORT_TYPE foreign key (TRANSPORT_TYPE_ID) references ERP_TRANSPORT_TYPE(ID);
alter table ERP_TRANSPORT add constraint FK_ERP_TRANSPORT_CURRENCY_BILLING foreign key (CURRENCY_BILLING_ID) references ERP_CURRENCY(ID);
alter table ERP_TRANSPORT add constraint FK_ERP_TRANSPORT_FORWARDER foreign key (FORWARDER_ID) references ERP_FORWARDER(ID);
create index IDX_ERP_TRANSPORT_COMPANY on ERP_TRANSPORT (COMPANY_ID);
create index IDX_ERP_TRANSPORT_TRANSPORT_TYPE on ERP_TRANSPORT (TRANSPORT_TYPE_ID);
create index IDX_ERP_TRANSPORT_CURRENCY_BILLING on ERP_TRANSPORT (CURRENCY_BILLING_ID);
create index IDX_ERP_TRANSPORT_FORWARDER on ERP_TRANSPORT (FORWARDER_ID);