alter table ERP_TRUCK_EQUIPMENT add constraint FK_ERP_TRUCK_EQUIPMENT_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID);
create index IDX_ERP_TRUCK_EQUIPMENT_TRANSPORT on ERP_TRUCK_EQUIPMENT (TRANSPORT_ID);
alter table ERP_TRUCK_EQUIPMENT add constraint FK_ERP_TRUCK_EQUIPMENT_CURRENCY foreign key (CURRENCY_ID) references ERP_CURRENCY(ID);
create index IDX_ERP_TRUCK_EQUIPMENT_CURRENCY on ERP_TRUCK_EQUIPMENT (CURRENCY_ID);
