alter table ERP_TRUCK_FORWARDERS add constraint FK_ERP_TRUCK_FORWARDERS_TRUCK_EQUIPMENT foreign key (TRUCK_EQUIPMENT_ID) references ERP_TRUCK_EQUIPMENT(ID);
alter table ERP_TRUCK_FORWARDERS add constraint FK_ERP_TRUCK_FORWARDERS_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID);
create index IDX_ERP_TRUCK_FORWARDERS_TRUCK_EQUIPMENT on ERP_TRUCK_FORWARDERS (TRUCK_EQUIPMENT_ID);
create index IDX_ERP_TRUCK_FORWARDERS_EMPLOYEE on ERP_TRUCK_FORWARDERS (EMPLOYEE_ID);
