alter table ERP_TRANSPORT_CLASS_ADR add constraint FK_ERP_TRANSPORT_CLASS_ADR_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID);
create index IDX_ERP_TRANSPORT_CLASS_ADR_TRANSPORT on ERP_TRANSPORT_CLASS_ADR (TRANSPORT_ID);
