alter table ERP_TRANSPORT_CREW_MEMBERS add constraint FK_ERP_TRANSPORT_CREW_MEMBERS_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID);
alter table ERP_TRANSPORT_CREW_MEMBERS add constraint FK_ERP_TRANSPORT_CREW_MEMBERS_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID);
create index IDX_ERP_TRANSPORT_CREW_MEMBERS_TRANSPORT on ERP_TRANSPORT_CREW_MEMBERS (TRANSPORT_ID);
create index IDX_ERP_TRANSPORT_CREW_MEMBERS_EMPLOYEE on ERP_TRANSPORT_CREW_MEMBERS (EMPLOYEE_ID);
