alter table ERP_TRANSPORT_TRAILERS add constraint FK_ERP_TRANSPORT_TRAILERS_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID);
alter table ERP_TRANSPORT_TRAILERS add constraint FK_ERP_TRANSPORT_TRAILERS_TRAILER foreign key (TRAILER_ID) references ERP_TRAILER(ID);
create index IDX_ERP_TRANSPORT_TRAILERS_TRANSPORT on ERP_TRANSPORT_TRAILERS (TRANSPORT_ID);
create index IDX_ERP_TRANSPORT_TRAILERS_TRAILER on ERP_TRANSPORT_TRAILERS (TRAILER_ID);
