alter table ERP_JOURNEY_CARGO add constraint FK_ERP_JOURNEY_CARGO_JOURNEY foreign key (JOURNEY_ID) references ERP_JOURNEY(ID);
alter table ERP_JOURNEY_CARGO add constraint FK_ERP_JOURNEY_CARGO_CARGO foreign key (CARGO_ID) references ERP_CARGO(ID);
create index IDX_ERP_JOURNEY_CARGO_JOURNEY on ERP_JOURNEY_CARGO (JOURNEY_ID);
create index IDX_ERP_JOURNEY_CARGO_CARGO on ERP_JOURNEY_CARGO (CARGO_ID);
