alter table ERP_JOURNEY_COMPOSITION add constraint FK_ERP_JOURNEY_COMPOSITION_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID);
create index IDX_ERP_JOURNEY_COMPOSITION_TRANSPORT on ERP_JOURNEY_COMPOSITION (TRANSPORT_ID);
