alter table ERP_TRANSPORT_STATE add constraint FK_ERP_TRANSPORT_STATE_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID);
create index IDX_ERP_TRANSPORT_STATE_TRANSPORT on ERP_TRANSPORT_STATE (TRANSPORT_ID);
