alter table ERP_MONITORING_SETTINGS add constraint FK_ERP_MONITORING_SETTINGS_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_ERP_MONITORING_SETTINGS_USER on ERP_MONITORING_SETTINGS (USER_ID);
