alter table ERP_TRANSPORT_STATE add constraint FK_ERP_TRANSPORT_STATE_TRUCK_EQUIPMENT foreign key (TRUCK_EQUIPMENT_ID) references ERP_TRUCK_EQUIPMENT(ID);
alter table ERP_TRANSPORT_STATE add constraint FK_ERP_TRANSPORT_STATE_JOURNEY foreign key (JOURNEY_ID) references ERP_JOURNEY(ID);
create index IDX_ERP_TRANSPORT_STATE_TRUCK_EQUIPMENT on ERP_TRANSPORT_STATE (TRUCK_EQUIPMENT_ID);
create index IDX_ERP_TRANSPORT_STATE_JOURNEY on ERP_TRANSPORT_STATE (JOURNEY_ID);
