alter table ERP_JOURNEY add constraint FK_ERP_JOURNEY_TRUCK_EQUIPMENT foreign key (TRUCK_EQUIPMENT_ID) references ERP_TRUCK_EQUIPMENT(ID);
alter table ERP_JOURNEY add constraint FK_ERP_JOURNEY_CURRENCY foreign key (CURRENCY_ID) references ERP_CURRENCY(ID);
create index IDX_ERP_JOURNEY_TRUCK_EQUIPMENT on ERP_JOURNEY (TRUCK_EQUIPMENT_ID);
create index IDX_ERP_JOURNEY_CURRENCY on ERP_JOURNEY (CURRENCY_ID);
