alter table ERP_JOURNEY_COMPOSITION add constraint FK_ERP_JOURNEY_COMPOSITION_TRUCK_EQUIPMENT foreign key (TRUCK_EQUIPMENT_ID) references ERP_TRUCK_EQUIPMENT(ID);
alter table ERP_JOURNEY_COMPOSITION add constraint FK_ERP_JOURNEY_COMPOSITION_JOURNEY foreign key (JOURNEY_ID) references ERP_JOURNEY(ID);
create index IDX_ERP_JOURNEY_COMPOSITION_TRUCK_EQUIPMENT on ERP_JOURNEY_COMPOSITION (TRUCK_EQUIPMENT_ID);
create index IDX_ERP_JOURNEY_COMPOSITION_JOURNEY on ERP_JOURNEY_COMPOSITION (JOURNEY_ID);
