alter table ERP_ACCESS_TO_CARGO add constraint FK_ERP_ACCESS_TO_CARGO_CARGO foreign key (CARGO_ID) references ERP_CARGO(ID);
alter table ERP_ACCESS_TO_CARGO add constraint FK_ERP_ACCESS_TO_CARGO_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID);
create index IDX_ERP_ACCESS_TO_CARGO_CARGO on ERP_ACCESS_TO_CARGO (CARGO_ID);
create index IDX_ERP_ACCESS_TO_CARGO_COMPANY on ERP_ACCESS_TO_CARGO (COMPANY_ID);
