ALTER TABLE ERP_TRANSPORTS_ACCESS ADD CONSTRAINT FK_ERP_TRANSPORTS_ACCESS_TRANSPORT FOREIGN KEY (TRANSPORT_ID) REFERENCES ERP_TRANSPORT(ID)^
ALTER TABLE ERP_TRANSPORTS_ACCESS ADD CONSTRAINT FK_ERP_TRANSPORTS_ACCESS_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES ERP_COMPANY(ID)^
CREATE INDEX IDX_ERP_TRANSPORT_ACCESS on ERP_TRANSPORTS_ACCESS (TRANSPORT_ID)^
CREATE INDEX IDX_ERP_COMPANY_ACCESS on ERP_TRANSPORTS_ACCESS (COMPANY_ID)^