alter table ERP_TRANSPORT add column AVAILABLE_FOR_ALL boolean ;
alter table ERP_TRANSPORT add column AVAILABLE_FOR_OWNER boolean ;

create index IDX_ERP_TRANSPORT_AVAILABLE_FOR_ALL on ERP_TRANSPORT (AVAILABLE_FOR_ALL) ^
create index IDX_ERP_TRANSPORT_AVAILABLE_FOR_OWNER on ERP_TRANSPORT (AVAILABLE_FOR_OWNER) ^