alter table ERP_TRAILER add column ACCESSIBLE_TO_ALL boolean ;
alter table ERP_TRAILER add column ACCESSIBLE_TO_OWNER boolean ^
create index IDX_ERP_TRAILER_ACCESSIBLE_TO_ALL on ERP_TRAILER (ACCESSIBLE_TO_ALL) ^
create index IDX_ERP_TRAILER_ACCESSIBLE_TO_OWNER on ERP_TRAILER (ACCESSIBLE_TO_OWNER) ^
update ERP_TRAILER set ACCESSIBLE_TO_OWNER = true where ACCESSIBLE_TO_OWNER is null;