UPDATE ERP_TRANSPORT SET
FORWARDER_ID = (SELECT EMPLOYEE_ID FROM ERP_TRANSPORT_FORWARD_TABLE WHERE TRANSPORT_ID = ERP_TRANSPORT.ID)^

alter table ERP_TRANSPORT add constraint FK_ERP_TRANSPORT_FORWARDER foreign key (FORWARDER_ID) references ERP_EMPLOYEE(ID)^
alter table ERP_TRAILER add constraint FK_ERP_TRAILER_FORWARDER foreign key (FORWARDER_ID) references ERP_EMPLOYEE(ID)^