alter table ERP_DEPARTMENT_EMPLOYEE add constraint FK_ERP_DEPARTMENT_EMPLOYEE_DEPARTMENT foreign key (DEPARTMENT_ID) references ERP_DEPARTMENT(ID);
alter table ERP_DEPARTMENT_EMPLOYEE add constraint FK_ERP_DEPARTMENT_EMPLOYEE_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID);
create index IDX_ERP_DEPARTMENT_EMPLOYEE_DEPARTMENT on ERP_DEPARTMENT_EMPLOYEE (DEPARTMENT_ID);
create index IDX_ERP_DEPARTMENT_EMPLOYEE_EMPLOYEE on ERP_DEPARTMENT_EMPLOYEE (EMPLOYEE_ID);
