alter table ERP_DEPARTMENT add constraint FK_ERP_DEPARTMENT_CHIEF foreign key (CHIEF_ID) references ERP_EMPLOYEE(ID);
alter table ERP_DEPARTMENT add constraint FK_ERP_DEPARTMENT_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID);
create index IDX_ERP_DEPARTMENT_CHIEF on ERP_DEPARTMENT (CHIEF_ID);
create index IDX_ERP_DEPARTMENT_COMPANY on ERP_DEPARTMENT (COMPANY_ID);
create index IDX_ERP_DEPARTMENT_PID on ERP_DEPARTMENT (PID) ;
