alter table ERP_ACCESS_TO_TRAILER add constraint FK_ERP_ACCESS_TO_TRAILER_TRAILER foreign key (TRAILER_ID) references ERP_TRAILER(ID);
alter table ERP_ACCESS_TO_TRAILER add constraint FK_ERP_ACCESS_TO_TRAILER_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID);
create index IDX_ERP_ACCESS_TO_TRAILER_TRAILER on ERP_ACCESS_TO_TRAILER (TRAILER_ID);
create index IDX_ERP_ACCESS_TO_TRAILER_COMPANY on ERP_ACCESS_TO_TRAILER (COMPANY_ID);
