alter table ERP_CARGO rename column end_point_index_id to end_point_index_id__UNUSED ;
alter table ERP_CARGO alter column end_point_index_id__UNUSED drop not null ;
drop index IDX_ERP_CARGO_END_POINT_INDEX ;
alter table ERP_CARGO rename column start_point_index_id to start_point_index_id__UNUSED ;
alter table ERP_CARGO alter column start_point_index_id__UNUSED drop not null ;
drop index IDX_ERP_CARGO_START_POINT_INDEX ;
alter table ERP_CARGO rename column delivery_date_delta to delivery_date_delta__UNUSED ;
alter table ERP_CARGO rename column end_longitude to end_longitude__UNUSED ;
alter table ERP_CARGO rename column end_latitude to end_latitude__UNUSED ;
alter table ERP_CARGO rename column start_longitude to start_longitude__UNUSED ;
alter table ERP_CARGO rename column start_latitude to start_latitude__UNUSED ;
alter table ERP_CARGO rename column delivery_date to delivery_date__UNUSED ;
alter table ERP_CARGO rename column delivery_building to delivery_building__UNUSED ;
alter table ERP_CARGO rename column delivery_street to delivery_street__UNUSED ;
alter table ERP_CARGO rename column delivery_city to delivery_city__UNUSED ;
alter table ERP_CARGO rename column delivery_country to delivery_country__UNUSED ;
alter table ERP_CARGO rename column end_address to end_address__UNUSED ;
alter table ERP_CARGO alter column end_address__UNUSED drop not null ;
alter table ERP_CARGO rename column dispatch_building to dispatch_building__UNUSED ;
alter table ERP_CARGO rename column dispatch_street to dispatch_street__UNUSED ;
alter table ERP_CARGO rename column dispatch_city to dispatch_city__UNUSED ;
alter table ERP_CARGO rename column dispatch_country to dispatch_country__UNUSED ;
alter table ERP_CARGO rename column start_address to start_address__UNUSED ;
alter table ERP_CARGO alter column start_address__UNUSED drop not null ;
alter table ERP_CARGO rename column guid to guid__UNUSED ;
alter table ERP_CARGO add column LOADING_TIME integer ;
