alter table ERP_CARGO_DELIVERY_POINT add constraint FK_ERP_CARGO_DELIVERY_POINT_POINT foreign key (POINT_ID) references ERP_POINT(ID);
alter table ERP_CARGO_DELIVERY_POINT add constraint FK_ERP_CARGO_DELIVERY_POINT_CARGO foreign key (CARGO_ID) references ERP_CARGO(ID);
create index IDX_ERP_CARGO_DELIVERY_POINT_POINT on ERP_CARGO_DELIVERY_POINT (POINT_ID);
create index IDX_ERP_CARGO_DELIVERY_POINT_CARGO on ERP_CARGO_DELIVERY_POINT (CARGO_ID);
