alter table ERP_CLIENT_CREDIT add constraint FK_ERP_CLIENT_CREDIT_TRANSPORT_OWNER foreign key (TRANSPORT_OWNER_ID) references ERP_COMPANY(ID);
alter table ERP_CLIENT_CREDIT add constraint FK_ERP_CLIENT_CREDIT_COUNTERPARTY foreign key (COUNTERPARTY_ID) references ERP_COMPANY(ID);
alter table ERP_CLIENT_CREDIT add constraint FK_ERP_CLIENT_CREDIT_JOURNEY foreign key (JOURNEY_ID) references ERP_JOURNEY(ID);
create index IDX_ERP_CLIENT_CREDIT_TRANSPORT_OWNER on ERP_CLIENT_CREDIT (TRANSPORT_OWNER_ID);
create index IDX_ERP_CLIENT_CREDIT_COUNTERPARTY on ERP_CLIENT_CREDIT (COUNTERPARTY_ID);
create index IDX_ERP_CLIENT_CREDIT_JOURNEY on ERP_CLIENT_CREDIT (JOURNEY_ID);
