alter table ERP_DELIVERY_COMPOSITION add constraint FK_ERP_DELIVERY_COMPOSITION_DELIVERY foreign key (DELIVERY_ID) references ERP_DELIVERY(ID);
alter table ERP_DELIVERY_COMPOSITION add constraint FK_ERP_DELIVERY_COMPOSITION_POINT foreign key (POINT_ID) references ERP_POINT(ID);
create index IDX_ERP_DELIVERY_COMPOSITION_DELIVERY on ERP_DELIVERY_COMPOSITION (DELIVERY_ID);
create index IDX_ERP_DELIVERY_COMPOSITION_POINT on ERP_DELIVERY_COMPOSITION (POINT_ID);
