alter table ERP_JOURNEY_COMPOSITION add constraint FK_ERP_JOURNEY_COMPOSITION_POINT foreign key (POINT_ID) references ERP_POINT(ID);
create index IDX_ERP_JOURNEY_COMPOSITION_POINT on ERP_JOURNEY_COMPOSITION (POINT_ID);
