alter table ERP_MUTUAL_SETTLEMENTS add constraint FK_ERP_MUTUAL_SETTLEMENTS_TRANSPORT_OWNER foreign key (TRANSPORT_OWNER_ID) references ERP_COMPANY(ID);
alter table ERP_MUTUAL_SETTLEMENTS add constraint FK_ERP_MUTUAL_SETTLEMENTS_JOURNEY foreign key (JOURNEY_ID) references ERP_JOURNEY(ID);
create index IDX_ERP_MUTUAL_SETTLEMENTS_TRANSPORT_OWNER on ERP_MUTUAL_SETTLEMENTS (TRANSPORT_OWNER_ID);
create index IDX_ERP_MUTUAL_SETTLEMENTS_JOURNEY on ERP_MUTUAL_SETTLEMENTS (JOURNEY_ID);
