alter table ERP_SERVICES_PAYMENT add constraint FK_ERP_SERVICES_PAYMENT_COUNTERPARTY foreign key (COUNTERPARTY_ID) references ERP_COMPANY(ID);
alter table ERP_SERVICES_PAYMENT add constraint FK_ERP_SERVICES_PAYMENT_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID);
create index IDX_ERP_SERVICES_PAYMENT_COUNTERPARTY on ERP_SERVICES_PAYMENT (COUNTERPARTY_ID);
create index IDX_ERP_SERVICES_PAYMENT_COMPANY on ERP_SERVICES_PAYMENT (COMPANY_ID);
