alter table ERP_POLYGON_POINT add constraint FK_ERP_POLYGON_POINT_POLYGON foreign key (POLYGON_ID) references ERP_POLYGON_MAP(ID);
create index IDX_ERP_POLYGON_POINT_POLYGON on ERP_POLYGON_POINT (POLYGON_ID);
