alter table ERP_TRANSPORT_AREA add constraint FK_ERP_TRANSPORT_AREA_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID);
alter table ERP_TRANSPORT_AREA add constraint FK_ERP_TRANSPORT_AREA_POLYGON foreign key (POLYGON_ID) references ERP_POLYGON_MAP(ID);
create index IDX_ERP_TRANSPORT_AREA_TRANSPORT on ERP_TRANSPORT_AREA (TRANSPORT_ID);
create index IDX_ERP_TRANSPORT_AREA_POLYGON on ERP_TRANSPORT_AREA (POLYGON_ID);
