alter table ERP_POLYGON_SEGMENT add constraint FK_ERP_POLYGON_SEGMENT_ON_POLYGON foreign key (POLYGON_ID) references ERP_POLYGON_MAP(ID);
alter table ERP_POLYGON_SEGMENT add constraint FK_ERP_POLYGON_SEGMENT_ON_START foreign key (START_ID) references ERP_POLYGON_POINT(ID) on delete CASCADE;
alter table ERP_POLYGON_SEGMENT add constraint FK_ERP_POLYGON_SEGMENT_ON_END foreign key (END_ID) references ERP_POLYGON_POINT(ID) on delete CASCADE;
create index IDX_ERP_POLYGON_SEGMENT_ON_POLYGON on ERP_POLYGON_SEGMENT (POLYGON_ID);
create index IDX_ERP_POLYGON_SEGMENT_ON_START on ERP_POLYGON_SEGMENT (START_ID);
create index IDX_ERP_POLYGON_SEGMENT_ON_END on ERP_POLYGON_SEGMENT (END_ID);
