-- begin ERP_TRANSPORT_TYPE
alter table ERP_TRANSPORT_TYPE add constraint FK_ERP_TRANSPORT_TYPE_PARENT_TYPE foreign key (PID) references ERP_TRANSPORT_TYPE(ID)^
create index IDX_ERP_TRANSPORT_TYPE_PID on ERP_TRANSPORT_TYPE (PID);
-- end ERP_TRANSPORT_TYPE
-- begin ERP_TRANSPORT
alter table ERP_TRANSPORT add constraint FK_ERP_TRANSPORT_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID)^
alter table ERP_TRANSPORT add constraint FK_ERP_TRANSPORT_TRANSPORT_TYPE foreign key (TRANSPORT_TYPE_ID) references ERP_TRANSPORT_TYPE(ID)^
alter table ERP_TRANSPORT add constraint FK_ERP_TRANSPORT_CURRENCY_BILLING foreign key (CURRENCY_BILLING_ID) references ERP_CURRENCY(ID)^
alter table ERP_TRANSPORT add constraint FK_ERP_TRANSPORT_FORWARDER foreign key (FORWARDER_ID) references ERP_EMPLOYEE(ID)^
alter table ERP_TRANSPORT add constraint FK_ERP_TRANSPORT_PHOTO foreign key (PHOTO_ID) references SYS_FILE(ID)^
alter table ERP_TRANSPORT add constraint FK_ERP_TRANSPORT_CATEGORY foreign key (CATEGORY_ID) references ERP_CATEGORY(ID)^
create index IDX_ERP_TRANSPORT_COMPANY on ERP_TRANSPORT (COMPANY_ID)^
create index IDX_ERP_TRANSPORT_TRANSPORT_TYPE on ERP_TRANSPORT (TRANSPORT_TYPE_ID)^
create index IDX_ERP_TRANSPORT_CURRENCY_BILLING on ERP_TRANSPORT (CURRENCY_BILLING_ID)^
create index IDX_ERP_TRANSPORT_FORWARDER on ERP_TRANSPORT (FORWARDER_ID)^
create index IDX_ERP_TRANSPORT_PHOTO on ERP_TRANSPORT (PHOTO_ID)^
create index IDX_ERP_TRANSPORT_CATEGORY on ERP_TRANSPORT (CATEGORY_ID)^
create index IDX_ERP_TRANSPORT_IS_FREE on ERP_TRANSPORT (IS_FREE) ^
create index IDX_ERP_TRANSPORT_AVAILABLE_FOR_OWNER on ERP_TRANSPORT (AVAILABLE_FOR_OWNER) ^
create index IDX_ERP_TRANSPORT_AVAILABLE_FOR_ALL on ERP_TRANSPORT (AVAILABLE_FOR_ALL) ^
-- end ERP_TRANSPORT
-- begin ERP_TRAILER
alter table ERP_TRAILER add constraint FK_ERP_TRAILER_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID)^
alter table ERP_TRAILER add constraint FK_ERP_TRAILER_CURRENCY_BILLING foreign key (CURRENCY_BILLING_ID) references ERP_CURRENCY(ID)^
alter table ERP_TRAILER add constraint FK_ERP_TRAILER_FORWARDER foreign key (FORWARDER_ID) references ERP_EMPLOYEE(ID)^
create index IDX_ERP_TRAILER_COMPANY on ERP_TRAILER (COMPANY_ID)^
create index IDX_ERP_TRAILER_CURRENCY_BILLING on ERP_TRAILER (CURRENCY_BILLING_ID)^
create index IDX_ERP_TRAILER_FORWARDER on ERP_TRAILER (FORWARDER_ID)^
create index IDX_ERP_TRAILER_IS_FREE on ERP_TRAILER (IS_FREE) ^
create index IDX_ERP_TRAILER_ACCESSIBLE_TO_ALL on ERP_TRAILER (ACCESSIBLE_TO_ALL) ^
create index IDX_ERP_TRAILER_ACCESSIBLE_TO_OWNER on ERP_TRAILER (ACCESSIBLE_TO_OWNER) ^
-- end ERP_TRAILER
-- begin ERP_EMPLOYEE
alter table ERP_EMPLOYEE add constraint FK_ERP_EMPLOYEE_ROLE foreign key (ROLE_ID) references ERP_EMPLOYEE_ROLE(ID)^
alter table ERP_EMPLOYEE add constraint FK_ERP_EMPLOYEE_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID)^
alter table ERP_EMPLOYEE add constraint FK_ERP_EMPLOYEE_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_ERP_EMPLOYEE_ROLE on ERP_EMPLOYEE (ROLE_ID)^
create index IDX_ERP_EMPLOYEE_COMPANY on ERP_EMPLOYEE (COMPANY_ID)^
create index IDX_ERP_EMPLOYEE_USER on ERP_EMPLOYEE (USER_ID)^
create index IDX_ERP_EMPLOYEE_IS_FREE on ERP_EMPLOYEE (IS_FREE) ^
-- end ERP_EMPLOYEE

-- begin ERP_CURRENCY_RATE
alter table ERP_CURRENCY_RATE add constraint FK_ERP_CURRENCY_RATE_CURRENCY foreign key (CURRENCY_ID) references ERP_CURRENCY(ID)^
create index IDX_ERP_CURRENCY_RATE_CURRENCY on ERP_CURRENCY_RATE (CURRENCY_ID)^
-- end ERP_CURRENCY_RATE
-- begin ERP_CARGO
alter table ERP_CARGO add constraint FK_ERP_CARGO_POINT foreign key (POINT_ID) references ERP_POINT(ID)^
alter table ERP_CARGO add constraint FK_ERP_CARGO_CURRENCY foreign key (CURRENCY_ID) references ERP_CURRENCY(ID)^
alter table ERP_CARGO add constraint FK_ERP_CARGO_TRANSPORT_TYPE foreign key (TRANSPORT_TYPE_ID) references ERP_TRANSPORT_TYPE(ID)^
alter table ERP_CARGO add constraint FK_ERP_CARGO_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID)^
alter table ERP_CARGO add constraint FK_ERP_CARGO_MANAGER foreign key (MANAGER_ID) references ERP_EMPLOYEE(ID)^
alter table ERP_CARGO add constraint FK_ERP_CARGO_CLIENT foreign key (CLIENT_ID) references ERP_COMPANY(ID)^
create index IDX_ERP_CARGO_POINT on ERP_CARGO (POINT_ID)^
create index IDX_ERP_CARGO_CURRENCY on ERP_CARGO (CURRENCY_ID)^
create index IDX_ERP_CARGO_TRANSPORT_TYPE on ERP_CARGO (TRANSPORT_TYPE_ID)^
create index IDX_ERP_CARGO_COMPANY on ERP_CARGO (COMPANY_ID)^
create index IDX_ERP_CARGO_MANAGER on ERP_CARGO (MANAGER_ID)^
create index IDX_ERP_CARGO_CLIENT on ERP_CARGO (CLIENT_ID)^
create index IDX_ERP_CARGO_ACCESSIBLE_TO_OWNER on ERP_CARGO (ACCESSIBLE_TO_OWNER) ^
create index IDX_ERP_CARGO_ACCESSIBLE_TO_ALL on ERP_CARGO (ACCESSIBLE_TO_ALL) ^
-- end ERP_CARGO
-- begin ERP_JOURNEY
alter table ERP_JOURNEY add constraint FK_ERP_JOURNEY_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID)^
alter table ERP_JOURNEY add constraint FK_ERP_JOURNEY_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID)^
alter table ERP_JOURNEY add constraint FK_ERP_JOURNEY_CURRENCY foreign key (CURRENCY_ID) references ERP_CURRENCY(ID)^
alter table ERP_JOURNEY add constraint FK_ERP_JOURNEY_FREIGHTER foreign key (FREIGHTER_ID) references ERP_COMPANY(ID)^
create index IDX_ERP_JOURNEY_TRANSPORT on ERP_JOURNEY (TRANSPORT_ID)^
create index IDX_ERP_JOURNEY_EMPLOYEE on ERP_JOURNEY (EMPLOYEE_ID)^
create index IDX_ERP_JOURNEY_CURRENCY on ERP_JOURNEY (CURRENCY_ID)^
create index IDX_ERP_JOURNEY_FREIGHTER on ERP_JOURNEY (FREIGHTER_ID)^
-- end ERP_JOURNEY
-- begin ERP_JOURNEY_COMPOSITION
alter table ERP_JOURNEY_COMPOSITION add constraint FK_ERP_JOURNEY_COMPOSITION_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID)^
alter table ERP_JOURNEY_COMPOSITION add constraint FK_ERP_JOURNEY_COMPOSITION_JOURNEY foreign key (JOURNEY_ID) references ERP_JOURNEY(ID)^
alter table ERP_JOURNEY_COMPOSITION add constraint FK_ERP_JOURNEY_COMPOSITION_POINT foreign key (POINT_ID) references ERP_POINT(ID)^
create index IDX_ERP_JOURNEY_COMPOSITION_TRANSPORT on ERP_JOURNEY_COMPOSITION (TRANSPORT_ID)^
create index IDX_ERP_JOURNEY_COMPOSITION_JOURNEY on ERP_JOURNEY_COMPOSITION (JOURNEY_ID)^
create index IDX_ERP_JOURNEY_COMPOSITION_POINT on ERP_JOURNEY_COMPOSITION (POINT_ID)^
-- end ERP_JOURNEY_COMPOSITION
-- begin ERP_JOURNEY_CARGO
alter table ERP_JOURNEY_CARGO add constraint FK_ERP_JOURNEY_CARGO_JOURNEY foreign key (JOURNEY_ID) references ERP_JOURNEY(ID)^
alter table ERP_JOURNEY_CARGO add constraint FK_ERP_JOURNEY_CARGO_CARGO foreign key (CARGO_ID) references ERP_CARGO(ID)^
create index IDX_ERP_JOURNEY_CARGO_JOURNEY on ERP_JOURNEY_CARGO (JOURNEY_ID)^
create index IDX_ERP_JOURNEY_CARGO_CARGO on ERP_JOURNEY_CARGO (CARGO_ID)^
-- end ERP_JOURNEY_CARGO
-- begin ERP_TRANSPORT_STATE
alter table ERP_TRANSPORT_STATE add constraint FK_ERP_TRANSPORT_STATE_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID)^
alter table ERP_TRANSPORT_STATE add constraint FK_ERP_TRANSPORT_STATE_JOURNEY foreign key (JOURNEY_ID) references ERP_JOURNEY(ID)^
create index IDX_ERP_TRANSPORT_STATE_TRANSPORT on ERP_TRANSPORT_STATE (TRANSPORT_ID)^
create index IDX_ERP_TRANSPORT_STATE_JOURNEY on ERP_TRANSPORT_STATE (JOURNEY_ID)^
-- end ERP_TRANSPORT_STATE
-- begin ERP_TRANSPORT_TRAILERS
alter table ERP_TRANSPORT_TRAILERS add constraint FK_ERP_TRANSPORT_TRAILERS_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID)^
alter table ERP_TRANSPORT_TRAILERS add constraint FK_ERP_TRANSPORT_TRAILERS_TRAILER foreign key (TRAILER_ID) references ERP_TRAILER(ID)^
create index IDX_ERP_TRANSPORT_TRAILERS_TRANSPORT on ERP_TRANSPORT_TRAILERS (TRANSPORT_ID)^
create index IDX_ERP_TRANSPORT_TRAILERS_TRAILER on ERP_TRANSPORT_TRAILERS (TRAILER_ID)^
-- end ERP_TRANSPORT_TRAILERS
-- begin ERP_TRANSPORT_DRIVERS
alter table ERP_TRANSPORT_DRIVERS add constraint FK_ERP_TRANSPORT_DRIVERS_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID)^
alter table ERP_TRANSPORT_DRIVERS add constraint FK_ERP_TRANSPORT_DRIVERS_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID)^
create index IDX_ERP_TRANSPORT_DRIVERS_TRANSPORT on ERP_TRANSPORT_DRIVERS (TRANSPORT_ID)^
create index IDX_ERP_TRANSPORT_DRIVERS_EMPLOYEE on ERP_TRANSPORT_DRIVERS (EMPLOYEE_ID)^
-- end ERP_TRANSPORT_DRIVERS
-- begin ERP_TRANSPORT_FORWARDERS
alter table ERP_TRANSPORT_FORWARDERS add constraint FK_ERP_TRANSPORT_FORWARDERS_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID)^
alter table ERP_TRANSPORT_FORWARDERS add constraint FK_ERP_TRANSPORT_FORWARDERS_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID)^
create index IDX_ERP_TRANSPORT_FORWARDERS_EMPLOYEE on ERP_TRANSPORT_FORWARDERS (EMPLOYEE_ID)^
create index IDX_ERP_TRANSPORT_FORWARDERS_TRANSPORT on ERP_TRANSPORT_FORWARDERS (TRANSPORT_ID)^
-- end ERP_TRANSPORT_FORWARDERS
-- begin ERP_TRANSPORT_CREW_MEMBERS
alter table ERP_TRANSPORT_CREW_MEMBERS add constraint FK_ERP_TRANSPORT_CREW_MEMBERS_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID)^
alter table ERP_TRANSPORT_CREW_MEMBERS add constraint FK_ERP_TRANSPORT_CREW_MEMBERS_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID)^
create index IDX_ERP_TRANSPORT_CREW_MEMBERS_TRANSPORT on ERP_TRANSPORT_CREW_MEMBERS (TRANSPORT_ID)^
create index IDX_ERP_TRANSPORT_CREW_MEMBERS_EMPLOYEE on ERP_TRANSPORT_CREW_MEMBERS (EMPLOYEE_ID)^
-- end ERP_TRANSPORT_CREW_MEMBERS
-- begin ERP_TRANSPORT_CLASS_ADR
alter table ERP_TRANSPORT_CLASS_ADR add constraint FK_ERP_TRANSPORT_CLASS_ADR_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID)^
create index IDX_ERP_TRANSPORT_CLASS_ADR_TRANSPORT on ERP_TRANSPORT_CLASS_ADR (TRANSPORT_ID)^
-- end ERP_TRANSPORT_CLASS_ADR

-- begin ERP_COMPANY
alter table ERP_COMPANY add constraint FK_ERP_COMPANY_ON_RETURN_AREA foreign key (RETURN_AREA_ID) references ERP_POLYGON_MAP(ID)^
alter table ERP_COMPANY add constraint FK_ERP_COMPANY_ON_ACTIVITIES_TYPE foreign key (ACTIVITIES_TYPE_ID) references ERP_ACTIVITIES_TYPE(ID)^
create unique index IDX_ERP_COMPANY_UK_PREFIX on ERP_COMPANY (PREFIX) where DELETE_TS is null ^
create index IDX_ERP_COMPANY_ON_RETURN_AREA on ERP_COMPANY (RETURN_AREA_ID)^
create index IDX_ERP_COMPANY_ON_ACTIVITIES_TYPE on ERP_COMPANY (ACTIVITIES_TYPE_ID)^
-- end ERP_COMPANY
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID)^
create index IDX_SEC_USER_COMPANY on SEC_USER (COMPANY_ID)^
-- end SEC_USER
-- begin ERP_MONITORING_SETTINGS
alter table ERP_MONITORING_SETTINGS add constraint FK_ERP_MONITORING_SETTINGS_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_ERP_MONITORING_SETTINGS_USER on ERP_MONITORING_SETTINGS (USER_ID)^
-- end ERP_MONITORING_SETTINGS
-- begin ERP_JOURNEY_STATE
alter table ERP_JOURNEY_STATE add constraint FK_ERP_JOURNEY_STATE_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table ERP_JOURNEY_STATE add constraint FK_ERP_JOURNEY_STATE_JOURNEY foreign key (JOURNEY_ID) references ERP_JOURNEY(ID)^
create index IDX_ERP_JOURNEY_STATE_USER on ERP_JOURNEY_STATE (USER_ID)^
create index IDX_ERP_JOURNEY_STATE_JOURNEY on ERP_JOURNEY_STATE (JOURNEY_ID)^
-- end ERP_JOURNEY_STATE
-- begin ERP_CONSTANT
create unique index IDX_ERP_CONSTANT_UK_CONSTANT_KEY on ERP_CONSTANT (CONSTANT_KEY) where DELETE_TS is null ^
-- end ERP_CONSTANT
-- begin ERP_ACCESS_TO_CARGO
alter table ERP_ACCESS_TO_CARGO add constraint FK_ERP_ACCESS_TO_CARGO_CARGO foreign key (CARGO_ID) references ERP_CARGO(ID)^
alter table ERP_ACCESS_TO_CARGO add constraint FK_ERP_ACCESS_TO_CARGO_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID)^
create index IDX_ERP_ACCESS_TO_CARGO_CARGO on ERP_ACCESS_TO_CARGO (CARGO_ID)^
create index IDX_ERP_ACCESS_TO_CARGO_COMPANY on ERP_ACCESS_TO_CARGO (COMPANY_ID)^
-- end ERP_ACCESS_TO_CARGO
-- begin ERP_ACCESS_TO_TRAILER
alter table ERP_ACCESS_TO_TRAILER add constraint FK_ERP_ACCESS_TO_TRAILER_TRAILER foreign key (TRAILER_ID) references ERP_TRAILER(ID)^
alter table ERP_ACCESS_TO_TRAILER add constraint FK_ERP_ACCESS_TO_TRAILER_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID)^
create index IDX_ERP_ACCESS_TO_TRAILER_TRAILER on ERP_ACCESS_TO_TRAILER (TRAILER_ID)^
create index IDX_ERP_ACCESS_TO_TRAILER_COMPANY on ERP_ACCESS_TO_TRAILER (COMPANY_ID)^
-- end ERP_ACCESS_TO_TRAILER
-- begin ERP_CARGO_DELIVERY_POINT
alter table ERP_CARGO_DELIVERY_POINT add constraint FK_ERP_CARGO_DELIVERY_POINT_POINT foreign key (POINT_ID) references ERP_POINT(ID)^
alter table ERP_CARGO_DELIVERY_POINT add constraint FK_ERP_CARGO_DELIVERY_POINT_CARGO foreign key (CARGO_ID) references ERP_CARGO(ID)^
create index IDX_ERP_CARGO_DELIVERY_POINT_POINT on ERP_CARGO_DELIVERY_POINT (POINT_ID)^
create index IDX_ERP_CARGO_DELIVERY_POINT_CARGO on ERP_CARGO_DELIVERY_POINT (CARGO_ID)^
-- end ERP_CARGO_DELIVERY_POINT
-- begin ERP_DEPARTMENT
alter table ERP_DEPARTMENT add constraint FK_ERP_DEPARTMENT_PID foreign key (PID_ID) references ERP_DEPARTMENT(ID)^
alter table ERP_DEPARTMENT add constraint FK_ERP_DEPARTMENT_CHIEF foreign key (CHIEF_ID) references ERP_EMPLOYEE(ID)^
alter table ERP_DEPARTMENT add constraint FK_ERP_DEPARTMENT_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID)^
create index IDX_ERP_DEPARTMENT_PID on ERP_DEPARTMENT (PID_ID)^
create index IDX_ERP_DEPARTMENT_CHIEF on ERP_DEPARTMENT (CHIEF_ID)^
create index IDX_ERP_DEPARTMENT_COMPANY on ERP_DEPARTMENT (COMPANY_ID)^
-- end ERP_DEPARTMENT
-- begin ERP_DEPARTMENT_EMPLOYEE
alter table ERP_DEPARTMENT_EMPLOYEE add constraint FK_ERP_DEPARTMENT_EMPLOYEE_DEPARTMENT foreign key (DEPARTMENT_ID) references ERP_DEPARTMENT(ID)^
alter table ERP_DEPARTMENT_EMPLOYEE add constraint FK_ERP_DEPARTMENT_EMPLOYEE_EMPLOYEE foreign key (EMPLOYEE_ID) references ERP_EMPLOYEE(ID)^
create index IDX_ERP_DEPARTMENT_EMPLOYEE_DEPARTMENT on ERP_DEPARTMENT_EMPLOYEE (DEPARTMENT_ID)^
create index IDX_ERP_DEPARTMENT_EMPLOYEE_EMPLOYEE on ERP_DEPARTMENT_EMPLOYEE (EMPLOYEE_ID)^
-- end ERP_DEPARTMENT_EMPLOYEE
-- begin ERP_MUTUAL_SETTLEMENTS
alter table ERP_MUTUAL_SETTLEMENTS add constraint FK_ERP_MUTUAL_SETTLEMENTS_TRANSPORT_OWNER foreign key (TRANSPORT_OWNER_ID) references ERP_COMPANY(ID)^
alter table ERP_MUTUAL_SETTLEMENTS add constraint FK_ERP_MUTUAL_SETTLEMENTS_JOURNEY foreign key (JOURNEY_ID) references ERP_JOURNEY(ID)^
create index IDX_ERP_MUTUAL_SETTLEMENTS_TRANSPORT_OWNER on ERP_MUTUAL_SETTLEMENTS (TRANSPORT_OWNER_ID)^
create index IDX_ERP_MUTUAL_SETTLEMENTS_JOURNEY on ERP_MUTUAL_SETTLEMENTS (JOURNEY_ID)^
-- end ERP_MUTUAL_SETTLEMENTS
-- begin ERP_TRANSPORTS_ACCESS
alter table ERP_TRANSPORTS_ACCESS add constraint FK_ERP_TRANSPORTS_ACCESS_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID)^
alter table ERP_TRANSPORTS_ACCESS add constraint FK_ERP_TRANSPORTS_ACCESS_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID)^
create index IDX_ERP_TRANSPORTS_ACCESS_TRANSPORT on ERP_TRANSPORTS_ACCESS (TRANSPORT_ID)^
create index IDX_ERP_TRANSPORTS_ACCESS_COMPANY on ERP_TRANSPORTS_ACCESS (COMPANY_ID)^
-- end ERP_TRANSPORTS_ACCESS
-- begin ERP_CLIENT_CREDIT
alter table ERP_CLIENT_CREDIT add constraint FK_ERP_CLIENT_CREDIT_ON_TRANSPORT_OWNER foreign key (TRANSPORT_OWNER_ID) references ERP_COMPANY(ID)^
alter table ERP_CLIENT_CREDIT add constraint FK_ERP_CLIENT_CREDIT_ON_COUNTERPARTY foreign key (COUNTERPARTY_ID) references ERP_COMPANY(ID)^
alter table ERP_CLIENT_CREDIT add constraint FK_ERP_CLIENT_CREDIT_ON_JOURNEY foreign key (JOURNEY_ID) references ERP_JOURNEY(ID)^
create index IDX_ERP_CLIENT_CREDIT_ON_TRANSPORT_OWNER on ERP_CLIENT_CREDIT (TRANSPORT_OWNER_ID)^
create index IDX_ERP_CLIENT_CREDIT_ON_COUNTERPARTY on ERP_CLIENT_CREDIT (COUNTERPARTY_ID)^
create index IDX_ERP_CLIENT_CREDIT_ON_JOURNEY on ERP_CLIENT_CREDIT (JOURNEY_ID)^
-- end ERP_CLIENT_CREDIT
-- begin ERP_SERVICES_PAYMENT
alter table ERP_SERVICES_PAYMENT add constraint FK_ERP_SERVICES_PAYMENT_COUNTERPARTY foreign key (COUNTERPARTY_ID) references ERP_COMPANY(ID)^
alter table ERP_SERVICES_PAYMENT add constraint FK_ERP_SERVICES_PAYMENT_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID)^
create index IDX_ERP_SERVICES_PAYMENT_COUNTERPARTY on ERP_SERVICES_PAYMENT (COUNTERPARTY_ID)^
create index IDX_ERP_SERVICES_PAYMENT_COMPANY on ERP_SERVICES_PAYMENT (COMPANY_ID)^
-- end ERP_SERVICES_PAYMENT
-- begin ERP_DELIVERY
alter table ERP_DELIVERY add constraint FK_ERP_DELIVERY_CARGO foreign key (CARGO_ID) references ERP_CARGO(ID)^
alter table ERP_DELIVERY add constraint FK_ERP_DELIVERY_JOURNEY foreign key (JOURNEY_ID) references ERP_JOURNEY(ID)^
alter table ERP_DELIVERY add constraint FK_ERP_DELIVERY_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID)^
alter table ERP_DELIVERY add constraint FK_ERP_DELIVERY_CURRENCY foreign key (CURRENCY_ID) references ERP_CURRENCY(ID)^
create index IDX_ERP_DELIVERY_CARGO on ERP_DELIVERY (CARGO_ID)^
create index IDX_ERP_DELIVERY_JOURNEY on ERP_DELIVERY (JOURNEY_ID)^
create index IDX_ERP_DELIVERY_TRANSPORT on ERP_DELIVERY (TRANSPORT_ID)^
create index IDX_ERP_DELIVERY_CURRENCY on ERP_DELIVERY (CURRENCY_ID)^
-- end ERP_DELIVERY
-- begin ERP_DELIVERY_COMPOSITION
alter table ERP_DELIVERY_COMPOSITION add constraint FK_ERP_DELIVERY_COMPOSITION_DELIVERY foreign key (DELIVERY_ID) references ERP_DELIVERY(ID)^
alter table ERP_DELIVERY_COMPOSITION add constraint FK_ERP_DELIVERY_COMPOSITION_POINT foreign key (POINT_ID) references ERP_POINT(ID)^
create index IDX_ERP_DELIVERY_COMPOSITION_DELIVERY on ERP_DELIVERY_COMPOSITION (DELIVERY_ID)^
create index IDX_ERP_DELIVERY_COMPOSITION_POINT on ERP_DELIVERY_COMPOSITION (POINT_ID)^
-- end ERP_DELIVERY_COMPOSITION
-- begin ERP_ENTRY_POINT
alter table ERP_ENTRY_POINT add constraint FK_ERP_ENTRY_POINT_POLYGON_MAP foreign key (POLYGON_MAP_ID) references ERP_POLYGON_MAP(ID)^
create index IDX_ERP_ENTRY_POINT_POLYGON_MAP on ERP_ENTRY_POINT (POLYGON_MAP_ID)^
-- end ERP_ENTRY_POINT
-- begin ERP_POLYGON_POINT
alter table ERP_POLYGON_POINT add constraint FK_ERP_POLYGON_POINT_POLYGON foreign key (POLYGON_ID) references ERP_POLYGON_MAP(ID)^
create index IDX_ERP_POLYGON_POINT_POLYGON on ERP_POLYGON_POINT (POLYGON_ID)^
-- end ERP_POLYGON_POINT
-- begin ERP_CATEGORY_AREA
alter table ERP_CATEGORY_AREA add constraint FK_ERP_CATEGORY_AREA_CATEGORY foreign key (CATEGORY_ID) references ERP_CATEGORY(ID)^
alter table ERP_CATEGORY_AREA add constraint FK_ERP_CATEGORY_AREA_POLYGON foreign key (POLYGON_ID) references ERP_POLYGON_MAP(ID)^
create index IDX_ERP_CATEGORY_AREA_CATEGORY on ERP_CATEGORY_AREA (CATEGORY_ID)^
create index IDX_ERP_CATEGORY_AREA_POLYGON on ERP_CATEGORY_AREA (POLYGON_ID)^
-- end ERP_CATEGORY_AREA
-- begin ERP_TRANSPORT_AREA
alter table ERP_TRANSPORT_AREA add constraint FK_ERP_TRANSPORT_AREA_TRANSPORT foreign key (TRANSPORT_ID) references ERP_TRANSPORT(ID)^
alter table ERP_TRANSPORT_AREA add constraint FK_ERP_TRANSPORT_AREA_POLYGON foreign key (POLYGON_ID) references ERP_POLYGON_MAP(ID)^
create index IDX_ERP_TRANSPORT_AREA_TRANSPORT on ERP_TRANSPORT_AREA (TRANSPORT_ID)^
create index IDX_ERP_TRANSPORT_AREA_POLYGON on ERP_TRANSPORT_AREA (POLYGON_ID)^
-- end ERP_TRANSPORT_AREA
-- begin ERP_CATEGORY
alter table ERP_CATEGORY add constraint FK_ERP_CATEGORY_ON_COMPANY foreign key (COMPANY_ID) references ERP_COMPANY(ID)^
create index IDX_ERP_CATEGORY_ON_COMPANY on ERP_CATEGORY (COMPANY_ID)^
-- end ERP_CATEGORY
-- begin ERP_POLYGON_SEGMENT
alter table ERP_POLYGON_SEGMENT add constraint FK_ERP_POLYGON_SEGMENT_ON_POLYGON foreign key (POLYGON_ID) references ERP_POLYGON_MAP(ID)^
alter table ERP_POLYGON_SEGMENT add constraint FK_ERP_POLYGON_SEGMENT_ON_START foreign key (START_ID) references ERP_POLYGON_POINT(ID) on delete CASCADE^
alter table ERP_POLYGON_SEGMENT add constraint FK_ERP_POLYGON_SEGMENT_ON_END foreign key (END_ID) references ERP_POLYGON_POINT(ID) on delete CASCADE^
create index IDX_ERP_POLYGON_SEGMENT_ON_POLYGON on ERP_POLYGON_SEGMENT (POLYGON_ID)^
create index IDX_ERP_POLYGON_SEGMENT_ON_START on ERP_POLYGON_SEGMENT (START_ID)^
create index IDX_ERP_POLYGON_SEGMENT_ON_END on ERP_POLYGON_SEGMENT (END_ID)^
-- end ERP_POLYGON_SEGMENT
